### ISSUE TITLE
Does not run with Nix 2.8

### ISSUE THREAD

**Issue by bobby285271** [jtojnar/what-changed#7]
Noticed this when running this on https://github.com/NixOS/nixpkgs/pull/169886, using `nixVersions.nix_2_8` on https://github.com/NixOS/nixpkgs/commit/90147b38081852ae46c79461edcebb1bbd372702.

```
$ nix run github:jtojnar/what-changed -- --format html between-versions evolution-data-server 3.44.0 3.44.1
error: attribute 'defaultApp.x86_64-linux' should have type 'derivation'
```

**Comment by jtojnar** [comment]
Seems to work now?

**Comment by bobby285271** [comment]
It works for me (nix_2_7, nix_2_8), thanks!
<sub>(With ff43acd810a5d175542461989a0205d9c8e7382e I think this should no longer work with nix_2_6 or other older versions, I guess it should be fine?)</sub>
